# Generated by Django 2.2.1 on 2019-09-24 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='JobBoard',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=255, unique=True)),
                ('company_email', models.EmailField(max_length=254)),
                ('job_title', models.CharField(max_length=255)),
                ('job_description', models.CharField(max_length=255)),
                ('salary', models.DecimalField(decimal_places=2, max_digits=6)),
                ('city', models.CharField(max_length=255)),
                ('state', models.CharField(max_length=255)),
                ('created_at', models.DateField()),
                ('is_avaiiable', models.BooleanField(default=True)),
            ],
        ),
    ]
