# Generated by Django 2.2.1 on 2019-09-24 16:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobboard',
            old_name='is_avaiiable',
            new_name='is_available',
        ),
    ]
